# Generated by Django 6.0.4 on 2026-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('bucket_size', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=10)),
                ('source', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Aggregate',
                'verbose_name_plural': 'Aggregates',
                'indexes': [models.Index(fields=['tenant_id', 'bucket_start', 'bucket_size'], name='eventapp_ag_tenant__fd18da_idx'), models.Index(fields=['tenant_id', 'bucket_size', 'source', 'event_type'], name='eventapp_ag_tenant__9389ee_idx'), models.Index(fields=['bucket_start', 'bucket_size'], name='eventapp_ag_bucket__a57d06_idx')],
                'unique_together': {('tenant_id', 'bucket_start', 'bucket_size', 'source', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='AggregationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('bucket_size', models.CharField(default='minute', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('events_processed', models.PositiveBigIntegerField(default=0)),
                ('aggregates_created', models.PositiveBigIntegerField(default=0)),
                ('aggregates_updated', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aggregation Job',
                'verbose_name_plural': 'Aggregation Jobs',
                'indexes': [models.Index(fields=['status', 'created_at'], name='eventapp_ag_status_9b17e4_idx'), models.Index(fields=['tenant_id', 'status'], name='eventapp_ag_tenant__898e92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('device', 'Device')], db_index=True, max_length=50)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('error', 'Error'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='eventapp_ev_tenant__99688e_idx'), models.Index(fields=['tenant_id', 'source', 'event_type', 'timestamp'], name='eventapp_ev_tenant__a3d97d_idx'), models.Index(fields=['tenant_id', 'created_at'], name='eventapp_ev_tenant__d99378_idx')],
                'unique_together': {('event_id', 'tenant_id')},
            },
        ),
    ]
